# Generated by Django 5.1.2 on 2025-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editora', models.CharField(max_length=100)),
                ('num_paginas', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
